name: Full update

on:
  schedule:
    - cron:  '30 18 */2 * *'
  workflow_dispatch:

jobs:
  full-build:
    runs-on: ubuntu-latest
    steps:
    - name: Get source code from master
      uses: actions/checkout@v4
      with:
        ref: master
        path: master

    - name: Get source code from adlist-maker
      uses: actions/checkout@v4
      with:
        ref: adlist-maker
        path: adlist-maker

    - name: Get latest upstream lists
      working-directory: adlist-maker
      run: |
        /bin/bash ./scripts/prepare-upstream.sh

    - name: Commit upstream changes
      working-directory: adlist-maker
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action[bot]"
        git add .
        git commit -m "Update upstream lists"
        git push

    - name: Build anti-AD lists
      working-directory: adlist-maker
      run: |
        /bin/bash ./scripts/build-list.sh

    - name: Commit anti-AD changes
      run: |
        mv -f ./adlist-maker/adblock-for-dnsmasq.conf ./master/
        mv -f ./adlist-maker/anti-ad-* ./master/
        cd ./master
        git config user.email "action@github.com"
        git config user.name "GitHub Action[bot]"
        git add .
        git commit -m "Auto renew anti-AD lists" -m "with upstream changes"
        git push
