name: Partial update

on:
  push:
    branches:
      - adlist-maker
    paths:
      - '**.php'
      - 'scripts/prepare-upstream.sh'
      - 'scripts/origin-files/base-dead-hosts.txt'
      - 'scripts/origin-files/base-src-easylist.txt'
      - 'scripts/origin-files/base-src-hosts.txt'
      - 'scripts/origin-files/base-src-strict-hosts.txt'
      - 'scripts/origin-files/whiterule-src-easylist.txt'
      - 'scripts/origin-files/wildcard-src-easylist.txt'

jobs:
  partial-build:
    runs-on: ubuntu-latest
    steps:
    - name: Get source code from master
      uses: actions/checkout@v4
      with:
        ref: master
        path: master

    - name: Get source code from adlist-maker
      uses: actions/checkout@v4
      with:
        ref: adlist-maker
        path: adlist-maker

    - name: Build anti-AD lists
      working-directory: adlist-maker
      run: |
        /bin/bash ./scripts/build-list.sh

    - name: Commit anti-AD changes
      run: |
        mv -f ./adlist-maker/adblock-for-dnsmasq.conf ./master/
        mv -f ./adlist-maker/anti-ad-* ./master/
        cd ./master
        git config user.email "action@github.com"
        git config user.name "GitHub Action[bot]"
        git add .
        git commit -m "Auto renew anti-AD lists" -m "without upstream changes"
        git push
